### ISSUE TITLE
Ballot Feedback

### ISSUE THREAD

**Issue by mehrdadmms** [Microflow-xyz/retroactive-pokt-goods-funding#127]
# Tasks
## Ballot page

- [x] Add remove button for projects added to the ballot 
- [x] Add hover for the project name, and make the project name smaller with dots (check Figma)
- [x] Dragging back project to application pool should be possible on the whole card

## Project's page

- [x] Add category to project's page 
- [x] Add to ballot button must go down 
- [x] Change "add to ballot" text 
- [x] in add to ballot section do the search when user clicks on add to ballot 
- [ ]
