### ISSUE TITLE
Ballot Copy changes

### ISSUE THREAD

**Issue by mehrdadmms** [Microflow-xyz/retroactive-pokt-goods-funding#129]
# Task 

- [x] Remove "extra" from tiers 
- [x] In the guide section it is written "shelf" it should be replaced with "tier". In general any mention of shelf/shelves should be replaced with tier/tiers
![Image](https://github.com/Microflow-xyz/retroactive-pokt-goods-funding/assets/35366864/01764e98-0df3-48b8-aafa-9c8a88ca38ca)
- [x] The search bar only works if I write the name exactly from the beginning. the regex must change it such way that if a project's name was "POKTnews" I can find it by searching "news" or if it was "NodeWallet, Node Pilot, DAN" I can find it by searching "Pilot"
- [x] Change the following texts
  - [x] Add 0-${missing.highest} projects (Can use extra capacity from upper shelves) -> Add ${missing.highest} more projects to this tier or another tier below.
  - [x] Add 0-${missing.highest} more projects (Can use extra capacity from upper shelves) -> Add ${missing.highest} more projects to this tier or another tier below.
  - [x] Can use the extra capacity from the upper shelves -> Can use the extra capacity of higher tiers
