### ISSUE TITLE
POKT Branding

### ISSUE THREAD

**Issue by mehrdadmms** [Microflow-xyz/retroactive-pokt-goods-funding#3]
# Goal
The site's branding should change according to POKT's visual assets.

# Tasks

- [ ] Add logo
- [ ] Add favicon
- [ ] Change the coloring
- [ ] Adjust all texts to be POKT related

**Comment by mehrdadmms** [comment]
- [ ] Fix the color based on guideline https://assets-global.website-files.com/651fe0a9a906d151784935f8/658b4891c4e4f1d64fca20ba_POKT_Brand_and_Style_Guidelines_v3.pdf

- [ ] Remove ballot button and move the create project button to its place 
- [ ] Make the project page and home page full width with padding like "create project page" 
- [ ] Restructure project page (according to new design by @Sepanta) 
- [ ] Logo times 0.7
- [ ] FavIcon must be the same as https://www.pokt.network/presskit
- [ ] Change tab title to "POKT RetroPGF"
- [ ] Make the selection visible 
<img width="484" alt="image" src="https://github.com/Microflow-xyz/retroactive-pokt-goods-funding/assets/35366864/4f6e0b94-f5de-4e18-aca9-08fb8d12833f">

- [ ] Add "voting" to menu section and make is disable. when users hover over it show "Voting hasn't started yet"

**Comment by mehrdadmms** [comment]
Unify font
<img width="230" alt="image" src="https://github.com/Microflow-xyz/retroactive-pokt-goods-funding/assets/35366864/9928c27b-455a-4b48-8305-27d34e9fc369">

**Comment by mehrdadmms** [comment]
Change this to "Built with :heart:  using EasyRetroPGF by Microflow"
<img width="231" alt="image" src="https://github.com/Microflow-xyz/retroactive-pokt-goods-funding/assets/35366864/8e47fa98-8f7f-4221-aae0-60d0601e02a7">

**Comment by mehrdadmms** [comment]
- [ ] change the errors UX according to the brand guideline 

<img width="1029" alt="image" src="https://github.com/Microflow-xyz/retroactive-pokt-goods-funding/assets/35366864/332e7902-1633-4936-b95b-26ead8845d14">
