### ISSUE TITLE
Feedback Section

### ISSUE THREAD

**Issue by mehrdadmms** [Microflow-xyz/retroactive-pokt-goods-funding#4]
# Goal 
Add a feedback section where users can comment their thoughts either anonymously or not.
As an example, you can check the discussion section of [this grant proposal ](https://proposals.deepfunding.ai/graduated/rejected/3047b3a1-f583-4e47-b877-80211e5181a0)

# How
- Change the layout and add a feedback section to each project
- Have the feedback saved in Postgres using Prisma 
- The feedback should be available to everyone who wants to post during the submission period and then should be only visible and accessible to voters after the submission period 

# Tasks

- [ ] Layout
- [x] Store information
- [x] Access Control Level 

# Figma
To be provided...

**Comment by mehrdadmms** [comment]
https://www.figma.com/file/x28TrzkBzDgJ5XNnE2zqnw/Design-file?type=design&node-id=19-1839&mode=design&t=LfUGexcQJvKeh0dh-0

**Comment by mehrdadmms** [comment]
## Feedback - May 1st, 2024 

- [ ] by toggling the button it doesn't change, it doesn't show whether it is active or not 
<img width="243" alt="image" src="https://github.com/Microflow-xyz/retroactive-pokt-goods-funding/assets/35366864/f229cb4c-9119-4146-af2d-6f7c14d09032">

- [ ] if the wallet is not connected I can't see any of the feedback
- [ ] Instead of writing "UNAUTHORIZED", write "Please connect your wallet" when the wallet is not connected 
<img width="1048" alt="image" src="https://github.com/Microflow-xyz/retroactive-pokt-goods-funding/assets/35366864/ac541bff-1bc6-4dfa-a0c5-4e829bb937ea">

- [ ] Add fallback photo
- [ ] ENS is not working 
<img width="1512" alt="image" src="https://github.com/Microflow-xyz/retroactive-pokt-goods-funding/assets/35366864/d4a33ab4-03b6-4243-ae75-0112b9b6504d">
<img width="1512" alt="image" src="https://github.com/Microflow-xyz/retroactive-pokt-goods-funding/assets/35366864/f045f108-b101-41fe-9560-a873ba5b2d2b">

- [ ] The 1000 char limit haven't been handled in the UI
<img width="1512" alt="Screenshot 2024-05-01 at 9 26 32 AM" src="https://github.com/Microflow-xyz/retroactive-pokt-goods-funding/assets/35366864/41cc6f01-e6ad-4f38-92c3-7aac9cae7134">

**Comment by mehrdadmms** [comment]
- [ ] like / dislike Buttons    work  as many times as I click on it, 
limitation needed => 1 reaction for each user.

**Comment by mehrdadmms** [comment]
- [ ] site doesn't load ENS image
