### ISSUE TITLE
DevOps

### ISSUE THREAD

**Issue by mehrdadmms** [Microflow-xyz/retroactive-pokt-goods-funding#7]
# Tasks

- [ ] Create Automated CI/CD for the code to be deployed
  - [ ] Prod
  - [ ] Dev
- [ ] Come up with an action plan for during the round 
- [ ] Ensure safety and security

**Comment by sumitdethe27** [comment]
Hello @mehrdadmms , can you give me a breif about the project and the issue, I want to work on this
