### ISSUE TITLE
Ballot Page part 2 

### ISSUE THREAD

**Issue by mehrdadmms** [Microflow-xyz/retroactive-pokt-goods-funding#81]
# Gaol
Finalize the Ballot flow 

# Tasks
## Frontend

- [ ] Denied permission page
- [ ] Are you sure pop up
- [ ] Submitted ballot page
- [ ] Revoke ballot 
- [ ] Success page
- [ ] Integration with the server side 

## Backend

- [ ] Voting logic
