### ISSUE TITLE
Markdown

### ISSUE THREAD

**Issue by mehrdadmms** [Microflow-xyz/retroactive-pokt-goods-funding#96]
# Goal 
We need to add markdown support for the contribution description and impact description.
<img width="1062" alt="image" src="https://github.com/Microflow-xyz/retroactive-pokt-goods-funding/assets/35366864/00bb7d9c-8fa2-4bbc-9a3d-8e38319eda1f">

# Task 
- [x] Add support for writing markdown
- [x] modify the markdown component to follow brand guideline
- [x] Modify the project page to show the markdown properly
- [x] Remove any restriction on description size 

# Bonus
Un-uglify it :))
<img width="831" alt="Screenshot 2024-05-28 at 11 39 19 PM" src="https://github.com/Microflow-xyz/retroactive-pokt-goods-funding/assets/35366864/f2007fe5-bf92-413a-b315-dd79d461f64f">

**Comment by mhsamie** [comment]
sp:3
