### ISSUE TITLE
Voting tally

### ISSUE THREAD

**Issue by mehrdadmms** [Microflow-xyz/retroactive-pokt-goods-funding#99]
# Goal 
Finalize the frontend of the voting tally. 

# Task

- [x] Implement the frontend side 
- [x] load attestations and show project stats
- [x] Show voter stats
- [x] Show time remaining

# Figma
https://www.figma.com/design/x28TrzkBzDgJ5XNnE2zqnw/Design-file?node-id=927-7667&t=lOtZLwUIPsjz5ZwL-4

**Comment by mhsamie** [comment]
sp:5
